blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/AvishkarPatil/IssueMatch/discussions
    about: Ask questions and discuss ideas
  - name: SWoC 2026
    url: https://swoc.tech
    about: Learn more about Social Winter of Code